const styles = `:root{font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;color:#172522;background:#f3f7f5}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(100%,440px);padding:32px;background:#fff;border:1px solid #dce6e2;border-radius:18px;box-shadow:0 14px 45px #17352b12}h1{font-size:26px;margin:0 0 8px}.muted{color:#667570;margin:0 0 22px}label{display:block;margin:16px 0 6px;font-weight:600}input{width:100%;padding:12px;border:1px solid #cbd8d3;border-radius:9px;font:inherit}input:focus{outline:3px solid #087f6e26;border-color:#087f6e}.check{display:flex;align-items:center;gap:9px;margin-top:14px}.check input{width:auto}button{width:100%;margin-top:20px;padding:12px;border:0;border-radius:9px;background:#087f6e;color:white;font:inherit;font-weight:700;cursor:pointer}button:disabled{opacity:.6}#message{min-height:1.5em;color:#a93a36}.links{display:flex;justify-content:space-between;gap:12px;margin-top:18px}.links a{color:#087f6e;text-decoration:none}.requirements{font-size:13px;color:#667570;margin:8px 0 0}`
function page(title, description, fields, submit, footer, script, extra = '') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${title} · Business WhatsApp</title><style>${styles}</style></head><body><main class="card"><h1>${title}</h1><p class="muted">${description}</p><form id="form">${fields}<button type="submit">${submit}</button><p id="message" role="status" aria-live="polite"></p></form>${footer}${extra}</main><script>${script}</script></body></html>`
}
function submitScript(endpoint, body, success) {
  return `document.getElementById('form').addEventListener('submit',async function(e){e.preventDefault();var button=e.currentTarget.querySelector('button'),m=document.getElementById('message');button.disabled=true;m.textContent='';try{var r=await fetch('${endpoint}',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(${body})}),d=await r.json();if(!r.ok)throw new Error(d.error||'The request could not be completed.');${success}}catch(x){m.textContent=x.message}finally{button.disabled=false}})`
}

export const LOGIN_PAGE = page('Welcome back', 'Sign in to manage your WhatsApp accounts and automations.',
  '<label for="email">Email</label><input id="email" type="email" autocomplete="email" required maxlength="254"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required maxlength="128"><label class="check"><input id="remember" type="checkbox"> Keep me signed in for 30 days</label>',
  'Sign in', '<div class="links"><a href="/forgot-password">Forgot password?</a><a href="/signup">Create account</a></div>',
  submitScript('/api/login', "{email:document.getElementById('email').value,password:document.getElementById('password').value,remember:document.getElementById('remember').checked}", "location.assign('/')"))

export const SIGNUP_PAGE = page('Create your account', 'Set up your workspace to connect a WhatsApp business account.',
  '<label for="fullName">Full name</label><input id="fullName" autocomplete="name" required minlength="2" maxlength="100"><label for="email">Email</label><input id="email" type="email" autocomplete="email" required maxlength="254"><label for="password">Password</label><input id="password" type="password" autocomplete="new-password" required minlength="12" maxlength="72"><p class="requirements">Use at least 12 characters. Long, unique passwords are safer.</p><label for="confirm">Confirm password</label><input id="confirm" type="password" autocomplete="new-password" required minlength="12" maxlength="72">',
  'Create account', '<div class="links"><span>Already registered?</span><a href="/login">Sign in</a></div>',
  submitScript('/api/signup', "{fullName:document.getElementById('fullName').value,email:document.getElementById('email').value,password:document.getElementById('password').value,confirmPassword:document.getElementById('confirm').value}", "location.assign('/')"))

export const FORGOT_PASSWORD_PAGE = page('Reset your password', 'Enter your account email. If it matches an account, we will email a secure reset link.',
  '<label for="email">Email</label><input id="email" type="email" autocomplete="email" required maxlength="254">',
  'Send reset link', '<div class="links"><a href="/login">Back to sign in</a><a href="/signup">Create account</a></div>',
  submitScript('/api/forgot-password', "{email:document.getElementById('email').value}", "m.style.color='#126039';m.textContent=d.message"))

export const RESET_PASSWORD_PAGE = page('Choose a new password', 'Use a new password to secure your account.',
  '<label for="password">New password</label><input id="password" type="password" autocomplete="new-password" required minlength="12" maxlength="72"><p class="requirements">Use at least 12 characters.</p><label for="confirm">Confirm new password</label><input id="confirm" type="password" autocomplete="new-password" required minlength="12" maxlength="72">',
  'Save new password', '<div class="links"><a href="/login">Back to sign in</a></div>',
  submitScript('/api/reset-password', "{token:new URLSearchParams(location.hash.slice(1)).get('token'),password:document.getElementById('password').value,confirmPassword:document.getElementById('confirm').value}", "history.replaceState(null,'',location.pathname);m.style.color='#126039';m.textContent='Password updated. Sign in with your new password.';setTimeout(function(){location.assign('/login')},1600)"))
