export const COMMAND_STYLE = String.raw`
.command-toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.command-toolbar p{flex:1;margin:0}.command-categories{display:grid;gap:16px}.command-category header{position:static;background:transparent;box-shadow:none;padding:0;backdrop-filter:none;justify-content:space-between}.command-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:12px;margin-top:16px}.command-item{border:1px solid var(--line);border-radius:12px;padding:16px;min-width:0}.command-item label{display:flex;align-items:center;gap:10px}.command-item code{font-size:16px;font-weight:700;color:var(--green)}.command-item p{font-size:14px;margin:8px 0}.command-item .command-usage{font-size:12px;overflow-wrap:anywhere}.command-unavailable{background:#f8f9fa;color:var(--muted)}.command-form{display:grid;gap:14px}.command-form fieldset{border:0;padding:0;margin:0;min-width:0}.command-form fieldset:disabled{opacity:.75}.command-form .field-grid{align-items:start}.command-form textarea{min-height:85px}.command-rules{display:grid;gap:12px}.command-rule{border:1px solid var(--line);padding:12px;border-radius:10px}.command-rule .field-grid{margin-bottom:8px}.command-warning{border-radius:9px;padding:12px;background:#fff5da;color:#6c5420}.command-boolean{display:flex;align-items:center;gap:9px}.command-details summary{cursor:pointer;font-weight:600}.command-details[open] summary{margin-bottom:16px}.command-feedback{min-height:22px}.command-stats{font-size:12px;color:var(--muted)}@media(max-width:600px){.command-category header{flex-wrap:wrap;align-items:flex-start}.command-toolbar>button{flex:1}.command-toolbar p{flex-basis:100%}}
`
export const COMMAND_PAGE = String.raw`
<section id="commands" class="view">
<div class="page-heading"><div><span class="eyebrow">Your account’s bot</span><h1>Bot Commands</h1><p class="muted">Choose the tools your business needs. New features start disabled.</p></div></div>
<div class="card command-toolbar"><p id="commandAccountSummary" class="muted">Select a WhatsApp account to manage its commands.</p><button class="secondary" type="button" onclick="loadBotCommands(true)">Reload settings</button><button id="saveCommandSettings" type="button" onclick="saveBotCommands()">Save account settings</button></div>
<p id="commandFeedback" class="form-feedback command-feedback" role="status" aria-live="polite"></p>
<p id="commandConflict" class="command-warning hidden" role="status">Settings changed on another device. Reload to review the latest version before saving.</p>
<div id="commandPanels" class="hidden"><form id="commandForm" class="command-form" onsubmit="event.preventDefault();saveBotCommands()"><fieldset id="commandOwnerFields">
<div class="card"><h2>Command access</h2><p class="help">The connected account can send owner commands from its WhatsApp or linked devices. Group administration also requires current administrator permissions.</p><div class="field-grid"><label>Command prefix<input id="commandPrefix" type="text" maxlength="4" value="."></label><label>Permitted users<textarea id="commandPermitted" placeholder="One WhatsApp member identifier per line"></textarea><small>Use a phone number with country code, or a verified member identifier ending in @lid.</small></label></div><details class="command-details"><summary>Cooldowns and media limits</summary><div class="field-grid"><label>Command cooldown (seconds)<input id="commandCooldown" type="number" min="1" max="3600"></label><label>Commands per chat per minute<input id="commandChatLimit" type="number" min="1" max="120"></label><label>Commands per account per minute<input id="commandAccountLimit" type="number" min="1" max="300"></label><label>Maximum media size (MB)<input id="commandMediaMB" type="number" min="1" max="16"></label><label>Maximum video duration (seconds)<input id="commandVideoSeconds" type="number" min="1" max="30"></label><label>Processing timeout (seconds)<input id="commandTimeout" type="number" min="5" max="60"></label></div></details></div>
<div id="commandCategories" class="command-categories"></div>
<div class="card"><h2>Basic commands</h2><p class="help">Help and status commands are available to the owner by default. Their access can be changed here.</p><div id="basicCommandCards" class="command-grid"></div></div>
<div class="card"><h2>Automatic replies</h2><p class="help">Replies work in private chats when the Autoreply command is enabled. They match whole words and phrases and have a cooldown to prevent loops.</p><div class="field-grid"><label class="command-boolean"><input id="commandAutoreply" type="checkbox">Enable reply rules</label><label>Reply cooldown (seconds)<input id="commandReplyCooldown" type="number" min="10" max="86400"></label></div><div id="commandReplyRules" class="command-rules"></div><button type="button" class="secondary" onclick="addCommandReplyRule()">Add reply rule</button></div>
<div class="card"><h2>Authorized broadcast lists</h2><p class="help">Use saved recipients with their permission. Broadcasts run through Automations, with a wait between recipients and confirmation for large lists.</p><label class="command-boolean"><input id="commandBroadcastConsent" type="checkbox">I confirm the selected recipients have opted in or otherwise authorized these messages.</label><div class="field-grid"><label>Wait between recipients (seconds)<input id="commandBroadcastDelay" type="number" min="5" max="3600"></label><label>Require confirmation from this many recipients<input id="commandBroadcastThreshold" type="number" min="1" max="100"></label></div><label>Saved recipient list<select id="commandBroadcastList" onchange="chooseCommandBroadcastList()"></select></label><label>List name<input id="commandBroadcastName" type="text" maxlength="80" placeholder="e.g. Customer updates"></label><div id="commandBroadcastRecipients" class="groupbox"></div><div class="actions"><button type="button" class="secondary" onclick="saveCommandBroadcastList()">Apply list to draft</button><button type="button" class="secondary" onclick="newCommandBroadcastList()">New list</button><button type="button" class="danger" onclick="deleteCommandBroadcastList()">Remove list</button></div><small>Save account settings to persist these lists.</small></div>
<div class="card"><h2>Status media permission</h2><label class="command-boolean"><input id="commandStatusConsent" type="checkbox">I have the sender’s permission to save accessible Status media.</label><p class="help">Statussave requires a quoted accessible status. View-once, expired and otherwise inaccessible media cannot be recovered. Temporary files are removed after sending the copy.</p></div>
</fieldset></form>
<div class="card"><h2>Group rules and welcomes</h2><p class="help">Enable the corresponding account command above, then configure each group. Deletion and removal require the connected account to be a group administrator.</p><label>WhatsApp group<select id="commandGroup" onchange="chooseCommandGroup()"></select></label><form id="commandGroupForm" onsubmit="event.preventDefault();saveCommandGroup()"><fieldset id="commandGroupFields" style="border:0;padding:0;min-width:0"><div class="field-grid"><label class="command-boolean"><input id="commandAntilink" type="checkbox">Moderate unauthorized links</label><label class="command-boolean"><input id="commandAntiword" type="checkbox">Moderate prohibited phrases</label><label>Allowed domains<textarea id="commandDomains" placeholder="example.com&#10;docs.example.com"></textarea></label><label>Prohibited words and phrases<textarea id="commandWords" placeholder="One word or phrase per line"></textarea></label></div><button type="button" class="secondary" onclick="clearCommandWords()">Clear phrases…</button><div class="field-grid"><label class="command-boolean"><input id="commandAntispam" type="checkbox">Moderate spam</label><label class="command-boolean"><input id="commandExemptAdmins" type="checkbox">Exempt group administrators</label><label>Spam window (seconds)<input id="commandSpamWindow" type="number" min="5" max="120"></label><label>Maximum messages per member per window<input id="commandSpamMax" type="number" min="3" max="100"></label><label>Repeated-message threshold<input id="commandSpamRepeats" type="number" min="3" max="20"></label><label>Warning cooldown (seconds)<input id="commandModerationCooldown" type="number" min="10" max="3600"></label><label>Moderation action<select id="commandModerationAction"><option value="warn">Warn</option><option value="delete">Delete where permitted</option><option value="warn-delete">Warn and delete where permitted</option></select></label><label>Warning threshold<input id="commandWarningThreshold" type="number" min="1" max="20"></label><label>When the warning threshold is reached<select id="commandEscalation"><option value="none">Keep warnings for review</option><option value="kick">Remove non-admin member where permitted</option></select></label></div><label class="command-boolean"><input id="commandWelcome" type="checkbox">Welcome new group members</label><label>Welcome message<textarea id="commandWelcomeTemplate" maxlength="1000"></textarea></label><p class="help">Use {member} and {group} placeholders. Duplicate welcome events are suppressed.</p><button type="submit" id="saveGroupCommandButton">Save group settings</button></fieldset></form><h3>Member warnings</h3><div id="commandWarnings"></div></div>
</div></section>
`
export const COMMAND_SCRIPT = String.raw`
var commandData=null,commandDataKey='',commandLoading=null,commandDirty=false,commandGroupDirty=false,commandSelectedGroup='',commandReplyDrafts=[],commandBroadcastDrafts={};
function commandKey(){return (S?.workspace?.id||'')+':'+accountId}
function commandFeedback(message,bad){var el=document.getElementById('commandFeedback');el.textContent=message;el.className='form-feedback command-feedback'+(bad?' err':'')}
function commandAvailable(c){return c.name!=='tomp3'||commandData.mediaAvailability.tomp3}
function clearBotCommandView(){commandData=null;commandDirty=false;commandGroupDirty=false;commandSelectedGroup='';commandReplyDrafts=[];commandBroadcastDrafts={};document.getElementById('commandPanels').classList.add('hidden');document.getElementById('commandConflict').classList.add('hidden');['commandCategories','basicCommandCards','commandReplyRules','commandBroadcastRecipients','commandBroadcastList','commandGroup','commandWarnings'].forEach(function(id){document.getElementById(id).innerHTML=''});document.getElementById('commandOwnerFields').disabled=true;document.getElementById('commandGroupFields').disabled=true;document.getElementById('saveCommandSettings').disabled=true}
function loadBotCommands(force){
  if(!accountId){clearBotCommandView();commandDataKey='';commandFeedback('');document.getElementById('commandAccountSummary').textContent='Connect or select a WhatsApp account first.';return Promise.resolve()}
  var key=commandKey(),id=accountId;if(commandLoading?.key===key)return commandLoading.promise;
  if(commandDataKey!==key){clearBotCommandView();commandDataKey=key;document.getElementById('commandAccountSummary').textContent='Loading the selected account…';commandFeedback('Loading command settings…')}
  var promise=api('/api/accounts/'+encodeURIComponent(id)+'/commands').then(function(data){
    if(commandKey()!==key)return;
    if(!force&&(commandDirty||commandGroupDirty)){document.getElementById('commandConflict').classList.toggle('hidden',data.revision===commandData?.revision);return}
    if(!force&&commandData&&document.getElementById('commands').contains(document.activeElement)&&/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement.tagName))return;
    commandData=data;commandDirty=false;commandGroupDirty=false;commandReplyDrafts=JSON.parse(JSON.stringify(data.config.autoreply.rules));commandBroadcastDrafts=JSON.parse(JSON.stringify(data.config.broadcast.lists));document.getElementById('commandConflict').classList.add('hidden');renderBotCommands();
    if(document.getElementById('commandFeedback').textContent==='Loading command settings…')commandFeedback('Settings are ready.');
  }).catch(function(e){if(commandKey()===key)commandFeedback(e.message,true)}).finally(function(){if(commandLoading?.key===key)commandLoading=null});
  commandLoading={key:key,promise:promise};return promise
}
function commandCard(c){var setting=commandData.config.commands[c.name],available=commandAvailable(c),stats=commandData.statistics.find(function(s){return s.command===c.name})||{successes:0,failures:0};return '<article class="command-item'+(available?'':' command-unavailable')+'"><label><input type="checkbox" class="command-toggle" data-command="'+esc(c.name)+'" '+(setting.enabled?'checked ':'')+(!available?'disabled ':'')+'><code>'+esc(commandData.config.prefix+c.name)+'</code>'+(available?'':'<span class="pill">Unavailable</span>')+'</label><p>'+esc(c.description)+'</p><p class="command-usage">'+esc(commandData.config.prefix+c.usage)+'</p>'+(!available?'<p>'+esc('FFmpeg is unavailable on this installation.')+'</p>':'')+'<label>Access<select class="command-permission" data-command="'+esc(c.name)+'" '+(['autoreply','schedule','broadcast','statussave'].includes(c.name)?'disabled':'')+'>'+[['owner','Account owner'],['admin','Group administrators'],['permitted','Permitted users']].map(function(pair){return '<option value="'+pair[0]+'" '+(setting.permission===pair[0]?'selected':'')+'>'+pair[1]+'</option>'}).join('')+'</select></label><p class="command-stats">'+stats.successes+' successful · '+stats.failures+' unsuccessful</p></article>'}
function renderBotCommands(){
  document.getElementById('commandPanels').classList.remove('hidden');
  var cfg=commandData.config,owner=S.workspace.role==='owner';document.getElementById('commandAccountSummary').textContent=(selectedAccount()?.name||'WhatsApp account')+' · '+(owner?'You manage these commands.':'Only the business owner can change these settings.');document.getElementById('commandOwnerFields').disabled=!owner;document.getElementById('commandGroupFields').disabled=!owner;document.getElementById('saveCommandSettings').disabled=!owner;
  var values={commandPrefix:cfg.prefix,commandPermitted:cfg.permittedUsers.join('\n'),commandCooldown:cfg.cooldownSeconds,commandChatLimit:cfg.perChatPerMinute,commandAccountLimit:cfg.perAccountPerMinute,commandMediaMB:cfg.media.maxBytes/(1024*1024),commandVideoSeconds:cfg.media.maxVideoSeconds,commandTimeout:cfg.media.timeoutSeconds,commandReplyCooldown:cfg.autoreply.cooldownSeconds,commandBroadcastDelay:cfg.broadcast.delaySeconds,commandBroadcastThreshold:cfg.broadcast.confirmationThreshold};Object.keys(values).forEach(function(id){document.getElementById(id).value=values[id]});
  document.getElementById('commandAutoreply').checked=cfg.autoreply.enabled;document.getElementById('commandBroadcastConsent').checked=cfg.broadcast.confirmedConsent;document.getElementById('commandStatusConsent').checked=cfg.statusSaveConsent;
  document.getElementById('commandCategories').innerHTML=['Group Administration','Media Tools','WhatsApp Utilities'].map(function(category){var commands=commandData.catalog.filter(function(c){return c.category===category}),available=commands.filter(commandAvailable),all=available.length&&available.every(function(c){return cfg.commands[c.name].enabled});return '<div class="card command-category"><header><h2>'+esc(category)+'</h2><label class="command-boolean"><input type="checkbox" class="command-category-toggle" data-category="'+esc(category)+'" '+(all?'checked':'')+'>Enable available commands</label></header><div class="command-grid">'+commands.map(commandCard).join('')+'</div></div>'}).join('');
  document.getElementById('basicCommandCards').innerHTML=commandData.catalog.filter(function(c){return c.category==='Basic'}).map(commandCard).join('');renderCommandReplyRules();renderCommandBroadcastLists();
  var selector=document.getElementById('commandGroup');selector.innerHTML='<option value="">Choose a WhatsApp group</option>'+commandData.groups.map(function(g){return '<option value="'+esc(g.id)+'">'+esc(g.subject)+'</option>'}).join('');selector.value=commandSelectedGroup;chooseCommandGroup();
}
function renderCommandReplyRules(){document.getElementById('commandReplyRules').innerHTML=commandReplyDrafts.map(function(r,i){return '<div class="command-rule" data-rule="'+i+'"><div class="field-grid"><label>Trigger<input type="text" class="command-rule-trigger" maxlength="100" value="'+esc(r.trigger)+'"></label><label>Reply<textarea class="command-rule-reply" maxlength="2000">'+esc(r.reply)+'</textarea></label></div><button type="button" class="secondary command-remove-rule" data-rule="'+i+'">Remove rule</button></div>'}).join('')}
function captureCommandReplyRules(){document.querySelectorAll('.command-rule').forEach(function(row){var draft=commandReplyDrafts[Number(row.dataset.rule)];draft.trigger=row.querySelector('input').value;draft.reply=row.querySelector('textarea').value})}
function addCommandReplyRule(){if(!commandData)return;captureCommandReplyRules();if(commandReplyDrafts.length>=50){commandFeedback('This account already has 50 reply rules.',true);return}commandReplyDrafts.push({id:crypto.randomUUID(),trigger:'',reply:''});commandDirty=true;renderCommandReplyRules()}
function renderCommandBroadcastLists(){var el=document.getElementById('commandBroadcastList'),previous=el.value;el.innerHTML='<option value="">New recipient list</option>'+Object.keys(commandBroadcastDrafts).map(function(name){return '<option value="'+esc(name)+'">'+esc(name)+'</option>'}).join('');el.value=Object.hasOwn(commandBroadcastDrafts,previous)?previous:'';chooseCommandBroadcastList()}
function chooseCommandBroadcastList(){var name=document.getElementById('commandBroadcastList').value,ids=commandBroadcastDrafts[name]||[];document.getElementById('commandBroadcastName').value=name;document.getElementById('commandBroadcastRecipients').innerHTML=(S.cfg.recipients||[]).map(function(r){return '<label><input type="checkbox" class="command-broadcast-recipient" value="'+esc(r.id)+'" '+(ids.includes(r.id)?'checked':'')+'> '+esc(r.name||'Saved contact')+'</label>'}).join('')||'<p class="muted">Add authorized contacts in Recipients &amp; Groups first.</p>'}
function newCommandBroadcastList(){document.getElementById('commandBroadcastList').value='';chooseCommandBroadcastList()}
function saveCommandBroadcastList(){var name=document.getElementById('commandBroadcastName').value.trim(),ids=[...document.querySelectorAll('.command-broadcast-recipient:checked')].map(function(el){return el.value});if(!name||!ids.length||['__proto__','constructor','prototype'].includes(name)){commandFeedback('Enter a list name and tick at least one authorized contact.',true);return}commandBroadcastDrafts[name]=ids;commandDirty=true;renderCommandBroadcastLists();document.getElementById('commandBroadcastList').value=name;chooseCommandBroadcastList();commandFeedback('List added to your draft. Save account settings to keep it.')}
function deleteCommandBroadcastList(){var name=document.getElementById('commandBroadcastList').value;if(!name)return;delete commandBroadcastDrafts[name];commandDirty=true;renderCommandBroadcastLists()}
function commandLines(id){return document.getElementById(id).value.split(/\r?\n/).map(function(x){return x.trim()}).filter(Boolean)}
function commandNumber(id){return Number(document.getElementById(id).value)}
function saveBotCommands(){
  if(!commandData||commandDataKey!==commandKey()||S.workspace.role!=='owner')return;var button=document.getElementById('saveCommandSettings');if(button.disabled)return;captureCommandReplyRules();
  var config=JSON.parse(JSON.stringify(commandData.config));config.prefix=document.getElementById('commandPrefix').value;config.permittedUsers=commandLines('commandPermitted').map(function(id){return /^\+?\d{8,15}$/.test(id)?id.replace(/^\+/,'')+'@s.whatsapp.net':id});config.cooldownSeconds=commandNumber('commandCooldown');config.perChatPerMinute=commandNumber('commandChatLimit');config.perAccountPerMinute=commandNumber('commandAccountLimit');config.media={maxBytes:commandNumber('commandMediaMB')*1024*1024,maxVideoSeconds:commandNumber('commandVideoSeconds'),timeoutSeconds:commandNumber('commandTimeout')};
  document.querySelectorAll('.command-toggle').forEach(function(el){config.commands[el.dataset.command].enabled=el.checked});document.querySelectorAll('.command-permission').forEach(function(el){config.commands[el.dataset.command].permission=el.value});config.autoreply={enabled:document.getElementById('commandAutoreply').checked,cooldownSeconds:commandNumber('commandReplyCooldown'),rules:commandReplyDrafts};config.broadcast={lists:commandBroadcastDrafts,confirmedConsent:document.getElementById('commandBroadcastConsent').checked,delaySeconds:commandNumber('commandBroadcastDelay'),confirmationThreshold:commandNumber('commandBroadcastThreshold')};config.statusSaveConsent=document.getElementById('commandStatusConsent').checked;
  var key=commandKey(),id=accountId;button.disabled=true;commandFeedback('Saving account settings…');return api('/api/accounts/'+encodeURIComponent(id)+'/commands','PUT',{revision:commandData.revision,config:config}).then(function(d){if(commandKey()!==key)return;commandDirty=false;commandData.config=d.config;commandData.revision=d.revision;commandFeedback(d.message);toast(d.message);if(!commandGroupDirty)return loadBotCommands(true)}).catch(function(e){if(commandKey()===key){commandFeedback(e.message,true);if(e.status===409)document.getElementById('commandConflict').classList.remove('hidden')}}).finally(function(){if(commandKey()===key)button.disabled=S.workspace.role!=='owner'})
}
function chooseCommandGroup(){if(!commandData)return;commandSelectedGroup=document.getElementById('commandGroup').value;commandGroupDirty=false;var group=commandData.groups.find(function(g){return g.id===commandSelectedGroup});document.getElementById('commandGroupForm').classList.toggle('hidden',!group);document.getElementById('commandWarnings').innerHTML='';if(!group)return;var s=group.settings;var checks={commandAntilink:s.antilink,commandAntiword:s.antiword,commandAntispam:s.antispam,commandExemptAdmins:s.exemptAdmins,commandWelcome:s.welcome};Object.keys(checks).forEach(function(id){document.getElementById(id).checked=checks[id]});var fields={commandDomains:s.allowedDomains.join('\n'),commandWords:s.words.join('\n'),commandSpamWindow:s.spamWindowSeconds,commandSpamMax:s.spamMaxMessages,commandSpamRepeats:s.spamRepeatThreshold,commandModerationCooldown:s.moderationCooldownSeconds,commandModerationAction:s.action,commandWarningThreshold:s.warningThreshold,commandEscalation:s.escalation,commandWelcomeTemplate:s.welcomeTemplate};Object.keys(fields).forEach(function(id){document.getElementById(id).value=fields[id]});document.getElementById('commandWarnings').innerHTML=group.warnings.map(function(w){return '<div class="row"><span class="grow">Member …'+esc(w.member.split('@')[0].slice(-4))+'</span><span class="pill">'+w.count+' warnings</span>'+(S.workspace.role==='owner'?'<button type="button" class="secondary command-reset-warning" data-member="'+esc(w.member)+'">Reset</button>':'')+'</div>'}).join('')||'<p class="muted">No warnings recorded for this group.</p>'}
function clearCommandWords(){if(!confirm('Clear the prohibited-word draft for this group? Save group settings to confirm the change.'))return;document.getElementById('commandWords').value='';commandGroupDirty=true}
function saveCommandGroup(){if(!commandData||!commandSelectedGroup||S.workspace.role!=='owner')return;var button=document.getElementById('saveGroupCommandButton');if(button.disabled)return;var body={revision:commandData.revision,config:{antilink:document.getElementById('commandAntilink').checked,antiword:document.getElementById('commandAntiword').checked,antispam:document.getElementById('commandAntispam').checked,exemptAdmins:document.getElementById('commandExemptAdmins').checked,welcome:document.getElementById('commandWelcome').checked,allowedDomains:commandLines('commandDomains'),words:commandLines('commandWords'),spamWindowSeconds:commandNumber('commandSpamWindow'),spamMaxMessages:commandNumber('commandSpamMax'),spamRepeatThreshold:commandNumber('commandSpamRepeats'),moderationCooldownSeconds:commandNumber('commandModerationCooldown'),action:document.getElementById('commandModerationAction').value,warningThreshold:commandNumber('commandWarningThreshold'),escalation:document.getElementById('commandEscalation').value,welcomeTemplate:document.getElementById('commandWelcomeTemplate').value}};var key=commandKey(),id=accountId,group=commandSelectedGroup;button.disabled=true;commandFeedback('Saving group settings…');return api('/api/accounts/'+encodeURIComponent(id)+'/commands/groups/'+encodeURIComponent(group),'PUT',body).then(function(d){if(commandKey()!==key)return;commandGroupDirty=false;commandData.revision=d.revision;var savedGroup=commandData.groups.find(function(g){return g.id===group});if(savedGroup)savedGroup.settings=body.config;commandFeedback(d.message);toast(d.message);if(!commandDirty)return loadBotCommands(true)}).catch(function(e){if(commandKey()===key)commandFeedback(e.message,true)}).finally(function(){if(commandKey()===key)button.disabled=S.workspace.role!=='owner'})}
document.getElementById('commands').addEventListener('input',function(event){if(event.target.closest('#commandGroupForm'))commandGroupDirty=true;else if(event.target.closest('#commandForm'))commandDirty=true});
document.getElementById('commands').addEventListener('change',function(event){var el=event.target;if(el.classList.contains('command-category-toggle')){document.querySelectorAll('.command-toggle').forEach(function(toggle){var command=commandData.catalog.find(function(c){return c.name===toggle.dataset.command});if(command.category===el.dataset.category&&!toggle.disabled)toggle.checked=el.checked});commandDirty=true}else if(el.closest('#commandForm'))commandDirty=true;else if(el.closest('#commandGroupForm'))commandGroupDirty=true});
document.getElementById('commands').addEventListener('click',function(event){var el=event.target.closest('button');if(!el)return;if(el.classList.contains('command-remove-rule')){captureCommandReplyRules();commandReplyDrafts.splice(Number(el.dataset.rule),1);commandDirty=true;renderCommandReplyRules()}if(el.classList.contains('command-reset-warning')){if(!commandSelectedGroup)return;var key=commandKey();api('/api/accounts/'+encodeURIComponent(accountId)+'/commands/groups/'+encodeURIComponent(commandSelectedGroup)+'/warnings/'+encodeURIComponent(el.dataset.member),'DELETE').then(function(d){if(commandKey()===key){commandFeedback(d.message);return loadBotCommands(true)}}).catch(function(e){commandFeedback(e.message,true)})}});
`
